CRDC_STUDY_NAMES:
  repository: CBIIT/bento-edps
  mdf_directory: model-desc
  package: edps/crdc_study_names
  latest_version: '1'
  versions:
  - version: '1'
    tag: '1'
  origin: CRDC
  code: CRDC0008
  property: crdc_study_names
  source_hash: e63364b3d9c479528bf9415547a126e70c2754f10679ce7b88ed0fb1f80b62ee
OBIB:
  repository: CBIIT/bento-edps
  mdf_directory: model-desc
  package: edps/obib_terms_valueset
  latest_version: '1'
  versions:
  - version: '1'
    tag: '1'
  origin: CRDC
  code: CRDC0002
  property: obib_terms_valueset
  by_reference_url_patterns:
  - bioportal.bioontology.org/ontologies/OBIB
  - ebi.ac.uk/ols4/ontologies/obib
  - obib
  source_hash: 2697fd269fa04445761f325332b609d5521459d2c2b167caea71b54b2f524b00
QA_TEST:
  repository: CBIIT/bento-edps
  mdf_directory: model-desc
  package: edps/qa_test_valueset
  latest_version: '1'
  versions:
  - version: '1'
    tag: '1'
  origin: CRDC
  code: CRDC0005
  property: qa_test_valueset
  source_hash: 155cf271213e7b4b2aa021e465c66848b50b94ed1a9f0fbb300d8cc070afe1f1
