NCIt:
  last_updated: '202602'
  date_format: '%Y%m'
caDSR:
  last_updated: '2019-04-20'
  date_format: '%Y-%m-%d'
promotion:
  last_promoted_sha: 2d0aa9f70eb1116f1ab3cefd5a6a1c618297b99b
  last_promoted_sha_stage_prod: 2d0aa9f70eb1116f1ab3cefd5a6a1c618297b99b
