name: Bento Deploy MDB Release
permissions: 
  contents: write
  id-token: write
  actions: read
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which Tier to Deploy'
        type: choice
        default: qa
        options:
          - qa
      release_number:
run-name: ${{ github.event_name == 'workflow_dispatch' && format('CDK_Release_Deploy-{0}.{1}', inputs.release_number, inputs.environment) || '' }}
jobs:
  mdb-diff:
    name: Show MDB Release Changeset
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Set up Node
      id: node-setup
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7     # v3.8.2
      with:
        node-version: "20"
 
    - name: Install CDK
      id: install-cdk
      run: |
        npm install -g aws-cdk@2.155.0

    - name: AWS OIDC Authentication
      id: aws-auth
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502     # v4.0.2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: ${{ github.actor }}

    - name: Get Artifacts From S3
      id: get-artifacts
      shell: bash
      run: |
        ver_string=${{ inputs.release_number }}
        app_version="${ver_string%.*}"

        aws s3api get-object --bucket bento-mdb-cdk --key $app_version/${{ inputs.environment }}.${{ inputs.release_number }}.zip ./${{ inputs.environment }}.${{ inputs.release_number }}.zip
        unzip ./${{ inputs.environment }}.${{ inputs.release_number }}.zip
        echo "Retreived CDK App: ${{ inputs.environment }}.${{ inputs.release_number }}"

    - name: Diff Stack Resources
      id: diff-cdk-stack
      env:
        AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: |
        cdk diff --app ${{ inputs.environment }}.${{ inputs.release_number }}

  mdb-deploy:
    name: Show MDB Release Changeset
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: mdb-diff
    if: success() # Only proceed if diff job succeeds
    steps:
    - name: Set up Node
      id: node-setup
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7     # v3.8.2
      with:
        node-version: "20"
 
    - name: Install CDK
      id: install-cdk
      run: |
        npm install -g aws-cdk@2.155.0

    - name: AWS OIDC Authentication
      id: aws-auth
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502     # v4.0.2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: ${{ github.actor }}

    - name: Get Artifacts From S3
      id: get-artifacts
      shell: bash
      run: |
        ver_string=${{ inputs.release_number }}
        app_version="${ver_string%.*}"

        aws s3api get-object --bucket bento-mdb-cdk --key $app_version/${{ inputs.environment }}.${{ inputs.release_number }}.zip ./${{ inputs.environment }}.${{ inputs.release_number }}.zip
        unzip ./${{ inputs.environment }}.${{ inputs.release_number }}.zip
        echo "Retreived CDK App: ${{ inputs.environment }}.${{ inputs.release_number }}"

    - name: Diff Stack Resources
      id: diff-cdk-stack
      env:
        AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: |
        cdk deploy --app ${{ inputs.environment }}.${{ inputs.release_number }} --require-approval=never --force

  #   - name: Slack Notification
  #     env:
  #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #     uses: act10ns/slack@87c73aef9f8838eb6feae81589a6b1487a4a9e08     # v1.6.0
  #     with:
  #       status: ${{ job.status }}
  #       steps: ${{ toJson(steps) }}
  #     if: always()